#!/bin/bash

PATH_TO_HERE="$HOME/dotfiles/"

if [ $# -eq 0 ] ; then
    echo "No arguments detected. Assuming 'dotlink -r -m -l'"
    isRemoving=true
    isMaking=true
    isLoading=true
fi

for key in "$@"
do
case $key in
    -r|--remove)
    isRemoving=true
    shift
    ;;
    -m|--make)
    isMaking=true
    shift
    ;;
    -l|--load)
    isLoading=true
    shift
    ;;
esac
done

export CYGWIN="winsymlinks:native"

# DOT_FILE_SELECTOR=.[^.]* # starts with a '.' and then is followed by something that is not '.' and then anything else.

FILE_SELECTOR=".bashrc
.bash_functions
.bash_history
.bash_path
.bash_profile
.bash_locations
.dircolors
.gitconfig
.inputrc
.minttyrc
.vimrc"

FOLDER_SELECTOR=".vim"

if [ "$isRemoving" = true ] ; then
    echo "[ Removing old links ]"
    for file in $FILE_SELECTOR
    do
        rm -f "$HOME/$file"
        echo -e "Removed ~/$file <- ( symlink to /dotfiles/$file )"
    done
    for folder in $FOLDER_SELECTOR
    do
        rm -rf "$HOME/$folder"
        echo -e "Removed ~/$folder <- ( symlink to /dotfiles/$folder )"
    done
fi

if [ "$isMaking" = true ] ; then
    echo "[ Creating Symbolic Links ]"
    for file in $FILE_SELECTOR
    do
        ln -sf "$PATH_TO_HERE$file" "$HOME/$file"
        echo -e "Created ~/$file <- ( symlink to /dotfiles/$file )"
    done
    for folder in $FOLDER_SELECTOR
    do
        ln -s "$PATH_TO_HERE$folder" "$HOME/$folder"
        echo -e "Created ~/$folder <- ( symlink to /dotfiles/$folder )"
    done
fi

if [ "$isLoading" = true ] ; then
    echo "[ Loading new links ]"
    source "$HOME/.bash_profile"
    echo "Sourced .bash_profile"
fi
