#!/bin/bash
if [ $# -eq 0 ] ; then
    echo "No arguments detected. Assuming 'dotlink -r -m -l'"
    isRemoving=true
    isMaking=true
    isLoading=true
fi

for key in "$@"
do
case $key in
    -r|--remove)
    isRemoving=true
    shift
    ;;
    -m|--make)
    isMaking=true
    shift
    ;;
    -l|--load)
    isLoading=true
    shift
    ;;
esac
done

export CYGWIN="winsymlinks:native"
# DOT_FILE_SELECTOR=.[^.]* # starts with a '.' and then is followed by something that is not '.' and then anything else.

FILE_SELECTOR=".bashrc
.bash_functions
.bash_history
.bash_path
.bash_profile
.dircolors
.gitconfig
.inputrc
.minttyrc
.vimrc"

if [ "$isRemoving" = true ] ; then
    echo "[ Removing old links ]"
    for filename in $FILE_SELECTOR
    do
        rm -f "$HOME/"$filename
        echo -e "Removed ~/"$filename" <- ( symlink to /dotfiles/"$filename" )"
    done
fi

if [ "$isMaking" = true ] ; then
    echo "[ Creating Symbolic Links ]"
    for filename in $FILE_SELECTOR
    do
        ln -s "./"$filename "$HOME/"$linkname
        echo -e "Created ~/"$filename" <- ( symlink to /dotfiles/"$filename" )"
    done
fi

if [ "$isLoading" = true ] ; then
    echo "[ Loading new links ]"
    source "$HOME/.bash_profile"
    echo "Sourced .bash_profile"
fi
